### ISSUE TITLE
filetree-show-cur-dir from a Dired buffer fails

### ISSUE THREAD

**Issue by vindarel** [knpatel401/filetree#10]
Hello me again, 

it fails with

```
filetree-expand-dir: Wrong type argument: stringp, nil
```

This time the function is a bit large so I didn't have a look!

**Comment by knpatel401** [comment]
Hi @vindarel, thanks for reporting.  

Wanted to get a little more information on how you're running the command.  The command is meant to be run in the filetree buffer (with the pointer on the directory you want to expand).  Are you possibly running from another buffer?  If so, then you'll get this (admittedly cryptic) error message--I'll plan to add an error check + a more clear msg if the command is run outside of the filetree buffer.

BTW, if you do want filetree to pull up the files in the directory of the current buffer, you can use filetree-show-cur-dir (or filetree-show-cur-dir-recursively for recursive version).

Thanks!
Ketan

**Comment by knpatel401** [comment]
Hi @vindarel,  

Sorry, I missed the title of your issue earlier, where you mentioned you ran the command filetree-show-cur-dir from the dired buffer.  Yeah, the filetree-show-cur-dir currently can only be run from a buffer that corresponds to a file.  If this functionality (i.e., show filetree for the dir pointed to by a dired buffer) users would find useful, I should be able to add special handling for the dired case in filetree-show-cur-dir/filetree-show-cur-dir-recursively.  Let me know if this is functionality you'd like added.

For now, I've at least added a more descriptive error message ([0b5025b0](https://github.com/knpatel401/filetree/commit/0b5025b0e072b6acf38d9b4a8dc4d4f019e6de63)), so it should let you know that the command (filetree-show-cur-dir) can only be run from a buffer that corresponds to a file.

Thanks!
Ketan

**Comment by knpatel401** [comment]
Just FYI, I added support for calling filetree-show-cur-dir (and the recursive version) from a dired buffer in the last couple commits [5e5065e17](https://github.com/knpatel401/filetree/commit/5e5065e173a56766c5bdb707f8a04d588543eaf6) and [0623432b](https://github.com/knpatel401/filetree/commit/0623432ba00b42e603ec399795266615e0fcd127).  Let me know if you try it and see any issues.

Thanks!
Ketan

**Comment by vindarel** [comment]
Hi, that's great, it's working, thanks! (and for the commit links)
