### ISSUE TITLE
file-tree-run-dired needs to be interactive

### ISSUE THREAD

**Issue by vindarel** [knpatel401/filetree#9]
Hello, pressing `d` returned an error:

> wrong type argument, commandp filetree-run-dired

telling it to be `(interactive)` fixed the issue.

Best

ps: awesome package O_o

**Comment by knpatel401** [comment]
Thanks a lot for pointing out the bug (and the solution :)).

I've pushed the fix to master ([ef6cb04d](https://github.com/knpatel401/filetree/commit/ef6cb04d7a250c4e390501cb7a10473f962521a3)).

Glad you like the package!
